apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
    - name: main-container
      image: thuong99/nginx_draft
      ports:
      - containerPort: 80
  initContainers:
    - name: init-container
      image: busybox
      command: ['sh', '-c', 'sleep 10']

# 1. Create a nginx app with Pod having InitContainerrunning command sleep for10s and main nginxcontainer
# kind create cluster --name=management
# k apply -f lession1.yaml
# k get pod
# k describe pod myapp
# k delete -f lession1.yaml