---
- name: Install and configure Nginx
  hosts: remote_hosts # Khai báo group host
  become: true # Cho phép chuyển sang quyền root khi thực hiện các task.
  roles:
    - ./roles/webserver # khai báo role thực hiện tác vụ
