apiVersion: v1
kind: Namespace
metadata:
  name: deployment

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: traning
  namespace: deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traning
  template:
    metadata:
      name: traning
      labels:
        app: traning
    spec:
      containers:
        - name: traning
          image: thuong99/nginx_draft
          ports:
            - containerPort: 80
