apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: main-container
        image: thuong99/nginx_draft
        ports:
        - containerPort: 80
      initContainers:
      - name: init-container
        image: busybox
        command: ['sh', '-c', 'sleep 10']
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80 # Cổng trên dịch vụ
    targetPort: 80 # Cổng mà ứng dụng trong Pod đang chạy
    nodePort: 30000  # Cổng trên node
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
