apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: testing-lession3 # namespace name
spec:
  containers:
    - image: thuong99/nginx_draft
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
