apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  type: NodePort
  ports:
    - port: 80  # Cổng trên dịch vụ
      targetPort: 80  # Cổng mà ứng dụng trong Pod đang chạy
      nodePort: 30000  # Cổng trên node
  selector:
    app: to-monitor # Chọn các Pod có label "app=my-app"
# mở port từ 30000 -> 32767, port phải khác nhau
