apiVersion: v1
kind: Service
metadata:
  name: name-service
spec:
  clusterIP: None
  selector:
    app: stateful-set
  ports:
    - name: http
      port: 80

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: name-stateful-set
spec:
  serviceName: name-service # the name of service
  replicas: 2
  selector:
    matchLabels:
      app: stateful-set
  template: # pod template
    metadata:
      labels:
        app: stateful-set
    spec:
      containers:
        - name: name-container
          image: thuong99/nginx_draft
          ports:
            - name: http
              containerPort: 80