Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  # Controlplane Nodes
  ControlplaneCount = 1
  (1..ControlplaneCount).each do |i|
      config.vm.define "controlplane-#{i}" do |controlplane|
          controlplane.vm.hostname = "controlplane-#{i}"
          controlplane.vm.network "private_network", ip: "172.16.1.1#{i}"

          controlplane.vm.provider "virtualbox" do |vb|
              vb.name = "controlplane-#{i}"
              vb.memory = 2048
              vb.cpus = 2
          end
          controlplane.vm.provision :shell, :path => "./common.sh"
          controlplane.vm.provision :shell, :path => "./controlplane.sh"
      end
  end

  # Worker Nodes
  WorkerCount = 1
  (1..WorkerCount).each do |i|
      config.vm.define "worker-#{i}" do |worker|
          worker.vm.hostname = "worker-#{i}"
          worker.vm.network "private_network", ip: "172.16.2.1#{i}"

          worker.vm.provider "virtualbox" do |vb|
              vb.name = "worker-#{i}"
              vb.memory = 2048
              vb.cpus = 2
          end
          worker.vm.provision :shell, :path => "./common.sh"
          worker.vm.provision :shell, :path => "./worker.sh"
      end
  end
end